FROM python:3.9-slim

WORKDIR /app

# Instalar dependencias
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copiar scripts
COPY scripts /scripts/

CMD ["python", "/scripts/load_data.py"]